### ISSUE TITLE
Add support for managed code / C#

### ISSUE THREAD

**Issue by tapika** [Microsoft/TestAdapterForGoogleTest#159]
In similar manner to GTA, I want to raise this also for TAfGT:

https://github.com/csoltenborn/GoogleTestAdapter/pull/274

My own git branch at the moment has all requires patches for being able to support managed code testing.

https://github.com/tapika/TestAdapterForGoogleTest

If you rollback history a little bit back - you will even find same patches being able on top of TAfGT. But I would propose to upgrade TAfGT to latest version of GTA, as that has better baseline code (See https://github.com/Microsoft/TestAdapterForGoogleTest/issues/121#issuecomment-475851031 )

There are two demo projects available for testing, one is located in my own fork, see project
https://github.com/tapika/TestAdapterForGoogleTest/tree/master/GoogleTestAdapter/TestCSharpClassic

Another one uses C# scripting technique and resides in separate repository:
https://github.com/tapika/syncProj

Both project should be compilable out of box.

If you miss bit more information on how things works - I've made sample video on subject:
Application Driven Unit Testing
https://www.youtube.com/watch?v=-miGEb7M3V8
Presentation slides and links in info of that video.

Environment currently should be working with Visual Studio 2017, but not yet with vs2019.
( https://github.com/Microsoft/TestAdapterForGoogleTest/issues/158 )

**Comment by tapika** [comment]
For Visual Studio 2019 - there is some glitch in test discovery, it hangs or does not work correctly - same functionality is working fine in vs2017. I suspect that this also relates to visual studio test platform, and correct place to raise this issue is on this github: https://github.com/Microsoft/vstest - however could relate also to test adapter for google test if not latest code resides in github.

    [17.4.2019 0:06:53 Informational] ------ Discover test started ------
    [17.4.2019 0:06:54 Error] System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.UpdateTestPlatform(Lazy`1 testPlatform, Boolean useSpecifiedAdapterLocations, Boolean areAllTestContainersCSharpOrVBOnly)
       at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.GetTestPlatformV2(Boolean useSpecifiedAdapterLocations, Boolean areAllTestContainersCSharpOrVBOnly)
    [17.4.2019 0:06:54 Error] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.VisualStudio.TestWindow.Controller.TestDiscoveryRequest.<CreateRequests>d__16.MoveNext()
       at Microsoft.VisualStudio.TestWindow.Controller.Request.<RunRequests>d__95.MoveNext()
       --- End of inner exception stack trace ---
       at Microsoft.VisualStudio.TestWindow.Controller.Request.<ProcessRequest>d__94.MoveNext()
    [17.4.2019 0:06:54 Informational] ========== Discover test finished: 0 found (0:00:00,446) ==========
    [17.4.2019 0:06:54 Error] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.VisualStudio.TestWindow.Controller.TestDiscoveryRequest.<CreateRequests>d__16.MoveNext()
       at Microsoft.VisualStudio.TestWindow.Controller.Request.<RunRequests>d__95.MoveNext()
       --- End of inner exception stack trace ---
       at Microsoft.VisualStudio.TestWindow.Controller.Request.<ProcessRequest>d__94.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.VisualStudio.TestWindow.Controller.RequestFactory.<ExecuteRequest>d__10.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.VisualStudio.TestWindow.Controller.RequestFactory.<Execute>d__11.MoveNext()
       --- End of inner exception stack trace ---
       at Microsoft.VisualStudio.TestWindow.Controller.Request.Wait(Int32 timeout)
       at Microsoft.VisualStudio.TestWindow.Controller.Request.Dispose(Boolean disposing)
       at Microsoft.VisualStudio.TestWindow.Controller.Request.Dispose()
       at Microsoft.VisualStudio.TestWindow.Controller.RequestFactory.<Execute>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.VisualStudio.TestWindow.Controller.Operation.<ExecuteRequestAsync>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.VisualStudio.TestWindow.Controller.DiscoveryOperation.<StartDiscoverTests>d__15.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.VisualStudio.TestWindow.Controller.DiscoverSelectedOperation.<ExecuteInternal>d__8.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.VisualStudio.TestWindow.Controller.Operation.<ExecuteWithEvents>d__38.MoveNext()

**Comment by tapika** [comment]
Please note that I'm also working on being able to determine C++ call stack, when application is running with managed code support - e.g. c++ + c++/cli, or c++ + c++/clr + c#.

https://github.com/tapika/stacktrace

It's not yet official fork - hopefully in future will become official.

Please notice that at the moment we have native C++ call stack determination, and only x64 platform, with main focus on windows at the moment.

Theoretically exception handling could be used also for google test "bootstrapper", but I'm still waiting for this ticket to kick in, otherwise need to switch test framework to something else.

**Comment by tapika** [comment]
https://github.com/tapika/stacktrace/blob/develop/example/csharp_crashy_window.xaml.cs
https://github.com/tapika/stacktrace/blob/develop/example/cpp_crashy_managed_dll/cpp_crashy_managed_dll.cpp

Contains samples of being able not only to catch native exception, but also survive it (by translating it to managed exception).
